version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: ai-chat-backend
    restart: unless-stopped
    environment:
      - HOST=0.0.0.0
      - PORT=8000
      - DEBUG=False
    env_file:
      - ./backend/.env
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    expose:
      - "8000"
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8000/health')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - ai-chat-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: ai-chat-frontend
    restart: unless-stopped
    expose:
      - "80"
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - ai-chat-network

  nginx:
    image: nginx:alpine
    container_name: ai-chat-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./ssl:/etc/nginx/ssl
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - frontend
      - backend
    networks:
      - ai-chat-network

  redis:
    image: redis:7-alpine
    container_name: ai-chat-redis
    restart: unless-stopped
    expose:
      - "6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD:-defaultpassword}
    networks:
      - ai-chat-network

volumes:
  redis_data:

networks:
  ai-chat-network:
    driver: bridge
