# Nixpacks config for Railway deployment
# https://nixpacks.com/docs

[phases.setup]
nixPkgs = ["nodejs", "python3", "nginx"]

[phases.install]
cmds = [
    "cd backend && pip install -r requirements.txt",
    "cd frontend && npm ci --only=production"
]

[phases.build]
cmds = [
    "cd frontend && npm run build",
    "mkdir -p /app/dist && cp -r frontend/dist/* /app/dist/"
]

[start]
cmd = "supervisord -c supervisord.conf"

[variables]
PORT = "80"
PYTHONUNBUFFERED = "1"
