# Render.yaml - конфигурация для автоматического деплоя полного приложения
services:
  # Полное приложение (Frontend + Backend + Nginx)
  - type: web
    name: ai-chat-app
    env: docker
    dockerfilePath: ./Dockerfile.render
    plan: free
    region: oregon
    envVars:
      - key: PORT
        value: 10000
      - key: OPENAI_API_KEY
        sync: false  # Будет задано через веб-интерфейс
      - key: ANTHROPIC_API_KEY
        sync: false  # Будет задано через веб-интерфейс
      - key: DEEPSEEK_API_KEY
        sync: false  # Будет задано через веб-интерфейс
      - key: PYTHONUNBUFFERED
        value: 1
    healthCheckPath: "/health"
    autoDeploy: true

  # Redis сервис (optional - для кеширования)
  - type: redis
    name: ai-chat-redis
    plan: free
    maxmemoryPolicy: allkeys-lru
